#!/bin/bash

if [ ! "$1" ]; then
    echo "You must specify an apk file"
    echo "usage : apk-details [APK FILE]"
    exit 1
fi
if [ ! -f "$1" ]; then
    echo File not found.
    exit 2
fi

APK_FILE=$1

patha=`ls -1 /opt/android-sdk/build-tools/ | tail -1`
aaptpath=/opt/android-sdk/build-tools/$patha

if [ ! $aaptpath ];then
    echo Android aapt tools not found 
    exit 3
fi

#PERMS
perms=`${aaptpath}/aapt d badging "$APK_FILE" | grep uses-permission | sed -e "s/.*://" -e "s/.*=//" -e "s/'//g" | tr "\n" "," | sed 's/,$//g'`
if [ $perms ]; then
    echo $perms
else
    echo "No permissions"
fi

#NAME
name=`${aaptpath}/aapt d badging "$APK_FILE" | grep application-label | head -1 | sed -e "s/.*://g" -e "s/'//g"`
if [ "$name" ]; then
    echo $name
else
    echo "_Unknown_"
fi
#VERNAME
ver=`${aaptpath}/aapt d badging "$APK_FILE" | grep versionName | sed -e "s/.*=//g" -e "s/'//g"`
if [ "$ver" ]; then
    echo $ver
else
    echo "_Error_"
fi
#VERCODE
${aaptpath}/aapt d badging "$APK_FILE" | grep versionCode | sed -e "s/.*versionCode=//g" -e "s/versionName=.*//g" -e "s/'//g"
#MINSDK
min=`${aaptpath}/aapt d badging "$APK_FILE" | grep sdkVersion | sed -e "s/sdkVersion://" -e "s/'//g"`
if [ "$min" ]; then
    echo $min
else
    echo "_Not_Specified_"
fi
#PKGNAME
${aaptpath}/aapt d badging "$APK_FILE" | grep package | head -1 | cut -d" "  -f2 | sed -e "s/.*=//" -e "s/'//g"
#ICON
ICON=`${aaptpath}/aapt d badging "$APK_FILE" | grep application-icon | tail -1 | sed -e "s/.*://" -e "s/'//g"`
#ICON_NAME
ICON_NAME=`${aaptpath}/aapt d badging "$APK_FILE" | grep application-icon | tail -1 | sed -e "s/.*://" -e "s/'//g" -e "s/.*\///g"`
#TMPFILE
TMPFILE=`mktemp -t XXXXXXX.png`
echo $TMPFILE
#MOVE ICON TO TMPFILE
unzip -j "$APK_FILE" $ICON -d /tmp/ > /dev/null && mv /tmp/$ICON_NAME $TMPFILE 
exit 0
