#!/bin/bash

if [ ! $1 ]; then
    echo "You must specify an apk file"
    echo "usage : apk-details [APK FILE]"
    exit 1
fi
if [ ! -f "$1" ]; then
    echo File not found.
    exit 2
fi

APK_FILE=$1

patha=`ls -1 /opt/android-sdk/build-tools/ | tail -1`
aaptpath=/opt/android-sdk/build-tools/$patha

if [ ! $aaptpath ];then
    echo Android aapt tools not found 
    exit 3
fi

#PERMS
${aaptpath}/aapt d badging "$APK_FILE" | grep uses-permission | sed -e "s/.*://" -e "s/.*=//" -e "s/'//g" | tr "\n" "," | sed 's/,$//g'
echo
#NAME
${aaptpath}/aapt d badging "$APK_FILE" | grep application-label | head -1 | sed -e "s/.*://g" -e "s/'//g" 
#VERNAME
${aaptpath}/aapt d badging "$APK_FILE" | grep versionName | sed -e "s/.*=//g" -e "s/'//g"
#VERCODE
${aaptpath}/aapt d badging "$APK_FILE" | grep versionCode | sed -e "s/.*versionCode=//g" -e "s/versionName=.*//g" -e "s/'//g"
#MINSDK
${aaptpath}/aapt d badging "$APK_FILE" | grep sdkVersion | sed -e "s/sdkVersion://" -e "s/'//g"
#PKGNAME
${aaptpath}/aapt d badging "$APK_FILE" | grep package | cut -d" "  -f2 | sed -e "s/.*=//" -e "s/'//g"
#ICON
ICON=`${aaptpath}/aapt d badging "$APK_FILE" | grep application-icon | tail -1 | sed -e "s/.*://" -e "s/'//g"`
#ICON_NAME
ICON_NAME=`${aaptpath}/aapt d badging "$APK_FILE" | grep application-icon | tail -1 | sed -e "s/.*://" -e "s/'//g" -e "s/.*\///g"`
#TMPFILE
TMPFILE=`mktemp -t XXXXXXX.png`
echo $TMPFILE
#MOVE ICON TO TMPFILE
unzip -j $APK_FILE $ICON -d /tmp/ > /dev/null && mv /tmp/$ICON_NAME $TMPFILE 
exit 0
